### ISSUE TITLE
Why the madVR Render can successfully block the live frame from VP

### ISSUE THREAD

**Issue by apperrs** [defl/videoprocessor#5]
Hi Dennis,
  Thanks for your works, and I have sucessfully compiled your project and ran VP with the madVR Render(below 134). 
  When I run VP with the madVR Render(above 134), VP always show black screen. I try to change the frame format, alter timestamp, rename the process name, and reduce the bit counts. But no effect.
  So I have not any way to let the madVR of high version running on the VP. Could you tell me some details about live source from capture card which madVR can detect.
  Thanks if you have any suggestions.

**Comment by defl** [comment]
Correct, VP doesn't work with newer versions of madvr, Check out AVS forums, they have a very active thread on this which will get you to the right version.

**Comment by apperrs** [comment]
Thanks for your reply. I knew the old version of madVR could work, but I want to continue developing VP on newer versions of madVR. That's why I wish to know how madVR can detect live source from capture card.
  If you can not say(or guess) anything, I will try other ways to achieve.

**Comment by defl** [comment]
Ah sorry misunderstood your intentions here.

I don't _know_ why it doesn't work anymore after madshi changed madvr to not allow VP. I do have a strong suspicion though and I suspect that if I'd want to I can get it to work (requires some rearchitecting). At that point there is no possible distinction anymore between VP and playback software.

This usage would always go against the T&C of madvr and I see no other recourse for madshi to end the open version of madvr as its a direct competitor to his commercial product with VP. Not something I want to do right now as there is no real gain, the last versions are not significantly better at HDR tonemapping etc last time I looked.

Something to consider before you embark. 🙂
