### ISSUE TITLE
MadVr testbuilds are not working

### ISSUE THREAD

**Issue by DereXo** [defl/videoprocessor#6]
Tried to use it with madVr. The testbuilds with much better hdr tonemap arent working. 
The first builds are saying: failed to connect pins. (madVRhdrMeasure118) 2021
The latest version seems to start but only shows a black screen. (madVRhdrMeasure205) 2024

only works with Version 9217 from 2018

**Comment by defl** [comment]
There are limitations indeed, doesn't work after a certain point with madvr. For support see https://www.avsforum.com/threads/videoprocessor.3206050/
